language: r
cache: packages
pandoc_version: 1.19.2.1

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh
  
deploy:
  provider: pages:git
  token: <encrypted token>
  edge: true # opt in to dpl v2
